import os
import time
duration=0
os.system('python3 /home/pi/Robot-Blueberry/robot-control/bothHand.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/hand_shake.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/left-right.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/touchHeadL.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/touchHeadR.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/circle.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/hayHay.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/no.py')
time.sleep(duration)
#os.system('python3 /home/pi/Robot-Blueberry/robot-control/touchNose.py')
#time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/hello.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/turnLeft.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/rightHand.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/turnRight.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/duldul.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/hug.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/yes.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/goForward.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/goBack.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/introduction.py')
time.sleep(duration)
#os.system('python3 /home/pi/Robot-Blueberry/robot-control/touchEad.py')
#time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/LeftHand.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/salute.py')
time.sleep(duration)
os.system('python3 /home/pi/Robot-Blueberry/robot-control/touchEye.py')
time.sleep(duration)



